### ISSUE TITLE
XMLCoding cannot build on Ubuntu 16.04

### ISSUE THREAD

**Issue by vkill** [LiveUI/S3#7]
Hi, the error messages

```
/usr/src/app/.build/checkouts/XMLCoding.git-5705070599758634965/Sources/XMLCoding/Encoder/XMLEncoder.swift:922:26: error: cannot convert value of type 'String' to type 'NSObject' in coercion
            return value.base64EncodedString() as NSObject
                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

**Comment by rafiki270** [comment]
thanks for this @vkill, I have had one more report of problems on linux and will be fixing this today/tomorrow latest, will ping you on discord when done

**Comment by rafiki270** [comment]
This has been fixed with https://github.com/LiveUI/XMLCoding/releases/tag/0.1.1

**Comment by rafiki270** [comment]
please upgrade your packages as this was a dependency, S3 now has a Dockerfile to test it's building fine
